services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: database-extraction-tool-app
    working_dir: /var/www/html
    ports:
      - "4000:80"
    volumes:
      - ./:/var/www/html
    environment:
      APP_URL: http://localhost:3000
      DB_HOST: 34.60.27.246
      DB_PORT: 1234
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: root
      DB_PASSWORD: example
